CREATE TABLE "CUSTOMERDATA"."EPSEWERAI_WOT_STG1" 
   ("TASK_UUID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"WOTASKTITLE" VARCHAR2(503 BYTE), 
	"PLNDCOMPDATE_DTTM" DATE, 
	"PLNDSTRTDATE_DTTM" DATE, 
	"WORKCLASSIFI_OI" NUMBER, 
	"FEED_STATUS" VARCHAR2(50 BYTE)) 
    
ALTER TABLE CUSTOMERDATA.EPSEWERAI_WOT_STG1
  ADD CONSTRAINT UQ_EPSEWERAI_WOT_STG1_TASKUUID
  UNIQUE (TASK_UUID);