CREATE OR REPLACE TRIGGER TRG_CR_INSP_NEW_TO_WOT_UPDATED
AFTER INSERT OR UPDATE OF FEED_STATUS ON CUSTOMERDATA.EPSEWERAI_CR_INSPECT
FOR EACH ROW
WHEN (NEW.FEED_STATUS = 'NEW')
BEGIN
  UPDATE CUSTOMERDATA.EPSEWERAI_WOT_STG stg
     SET stg.FEED_STATUS = 'UPDATED'
   WHERE stg.TASK_UUID      = HEXTORAW(UPPER(REPLACE(:NEW.PROJECT_SID,     '-', '')))
     AND stg.WORKORDER_UUID = HEXTORAW(UPPER(REPLACE(:NEW.WORK_ORDER_UUID, '-', '')))
     AND NVL(stg.FEED_STATUS, '~') <> 'UPDATED';
END;
