CREATE TABLE "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" 
   (	"PROJECT_SID" VARCHAR2(36 BYTE), 
	"INSPECTION_TYPE" VARCHAR2(5 BYTE), 
	"INSPECTIONID" VARCHAR2(36 BYTE), 
    "INSPECTION_SID" VARCHAR2(50 BYTE),
	"WORK_ORDER_UUID" VARCHAR2(36 BYTE),
	"WORKORDER" VARCHAR2(15 BYTE), 
	"PROJECT" VARCHAR2(503 BYTE), 
	"PO_NUMBER" VARCHAR2(50 BYTE), 
	"ADDITIONAL_INFORMATION" CLOB, 
	"PIPE_SEGMENT_REFERENCE" VARCHAR2(15 BYTE), 
	"LATERAL_SEGMENT_REFERENCE" VARCHAR2(15 BYTE), 
	"MANHOLE_NUMBER" VARCHAR2(15 BYTE), 
	"MATERIAL" VARCHAR2(200 BYTE), 
	"PIPE_USE" VARCHAR2(50 BYTE), 
	"COVER_SHAPE" VARCHAR2(20 BYTE), 
	"UPSTREAM_MH" VARCHAR2(15 BYTE), 
	"DOWNSTREAM_MH" VARCHAR2(15 BYTE), 
	"FACILITY_TYPE" NUMBER, 
	"FACILITY_ID" VARCHAR2(200 BYTE), 
	"FACILITYOI" NUMBER, 
	"PIP_TYPE" VARCHAR2(200 BYTE), 
	"SHAPE" VARCHAR2(20 BYTE), 
	"ACCESS_TYPE" VARCHAR2(50 BYTE), 
	"MH_USE" VARCHAR2(50 BYTE), 
	"WALL_MATERIAL" VARCHAR2(20 BYTE), 
	"BENCH_MATERIAL" VARCHAR2(20 BYTE), 
	"CHANNEL_MATERIAL" VARCHAR2(20 BYTE), 
	"WALL_BYSIZE" NUMBER, 
	"WALL_DEPTH" NUMBER, 
	"ELEVATION" NUMBER, 
	"FRAME_MATERIAL" VARCHAR2(100 BYTE), 
	"HEIGHT" NUMBER, 
	"UP_ELEVATION" NUMBER, 
	"UP_GRADE_TO_INVERT" NUMBER, 
	"DOWN_ELEVATION" NUMBER, 
	"DOWN_GRADE_TO_INVERT" NUMBER, 
	"STREET" VARCHAR2(400 BYTE), 
	"TOTAL_LENGTH" NUMBER, 
	"YEAR_CONSTRUCTED" NUMBER, 
	"SIZE" VARCHAR2(100 BYTE), 
	"DRAINAGE_AREA" VARCHAR2(200 BYTE), 
	"UNKNOWN_TYPE" NUMBER, 
	"CREATEDATE_DTTM" DATE, 
	"LASTUPDATE_DTTM" DATE, 
	"FEED_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IVARA_DATA" 
 LOB ("ADDITIONAL_INFORMATION") STORE AS BASICFILE (
  TABLESPACE "IVARA_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" ."INSPECTION_SID" IS 'SewerAI inspection.sid from Pioneer(unique, GUID-like)';
   COMMENT ON COLUMN "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" ."INSPECTIONID" IS 'Ivara Inspection.sid (unique, GUID-like)';
   
--Two indexes on the EPSEWERAI_CR_INSPECT table to keep the data clean and make lookups faster: 
--the unique index on INSPECTIONID makes sure the same inspection record isn’t inserted more than once, 
--and the unique index on (PROJECT_SID, INSPECTIONID) ensures an inspection can’t be duplicated within the same project 
--while also speeding up queries that search by project and inspection together.

  CREATE UNIQUE INDEX "CUSTOMERDATA"."UX_CR_INSPECT_INSPID" ON "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" ("INSPECTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IVARA_DATA" ;

 -- CREATE UNIQUE INDEX "CUSTOMERDATA"."UX_CR_INSPECT_PROJ_INSP" ON "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" ("PROJECT_SID", "INSPECTIONID") 
 -- PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 -- STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 -- PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 -- BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 -- TABLESPACE "IVARA_DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "IVARA"."TRG_CR_INSPECT_UPD_WOT_STG1" 
AFTER INSERT ON CUSTOMERDATA.EPSEWERAI_CR_INSPECT
FOR EACH ROW
BEGIN
  UPDATE CUSTOMERDATA.EPSEWERAI_WOT_STG1 w
     SET w.feed_status = 'UPDATED'
   WHERE w.task_uuid = REPLACE(:NEW.project_sid, '-', '')
     AND NVL(w.feed_status, '~') <> 'UPDATED';
END;

/
ALTER TRIGGER "IVARA"."TRG_CR_INSPECT_UPD_WOT_STG1" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "CUSTOMERDATA"."TRG_CR_INSPECT_UPD_WOT_STG1" 
AFTER INSERT ON CUSTOMERDATA.EPSEWERAI_CR_INSPECT
FOR EACH ROW
BEGIN
  UPDATE CUSTOMERDATA.EPSEWERAI_WOT_STG1 w
     SET w.feed_status = 'UPDATED'
   WHERE UPPER(w.task_uuid) = REPLACE(UPPER(:NEW.project_sid), '-', '')
     AND NVL(w.feed_status, '~') <> 'UPDATED';
END;



/
ALTER TRIGGER "CUSTOMERDATA"."TRG_CR_INSPECT_UPD_WOT_STG1" ENABLE;

GRANT INSERT ON "CUSTOMERDATA"."EPSEWERAI_CR_INSPECT" TO "MNT";
