-- Create the lookup table (2 columns + virtual normalization)

CREATE TABLE CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (
    ivara_shape    VARCHAR2(100 CHAR) NOT NULL,
    pioneers_code  VARCHAR2(5 CHAR)   NOT NULL
);

INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('ARCH TYPE "A"', 'A');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('ARCH TYPE "B"', 'A');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('ARCH TYPE "C"', 'A');

INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('BASKET HANDLE', 'Z');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('BOX SECTION', 'S');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('CIRCULAR', 'C');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('DOUBLE BARREL PIPE', 'Z');

INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('EGG', 'E');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('ELIPTICAL', 'O');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('EYE', 'E');

INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('HIGH HEAD', 'Z');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('INNER CIRCULAR', 'C');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('MONOLITHIC', 'A');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('OVAL', 'O');

INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('RECTANGULAR', 'R');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('UNKNOWN', 'Z');

-- Second block mappings
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('BOX', 'S');
INSERT INTO CUSTOMERDATA.EPSEWERAI_SHAPE_CODE (ivara_shape, pioneers_code) VALUES ('NOT CODED', 'Z');

COMMIT;

SELECT * FROM CUSTOMERDATA.EPSEWERAI_SHAPE_CODE;