CREATE TABLE CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (
  ivara_material   VARCHAR2(200) CONSTRAINT material_code_xref_uk UNIQUE,
  pioneers_code    VARCHAR2(20)  NOT NULL
);


-- Bulk insert all mappings (keys are normalized to UPPERCASE)
-- Optional: start clean
--TRUNCATE TABLE CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE;

-- Bulk insert all mappings (keys are normalized to UPPERCASE)
INSERT ALL
  -- Original full set
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('ASBESTOS CEMENT PIPE', 'AC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('BRICK', 'BR')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CAST IRON PIPE', 'CAS')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CLAY TILE PIPE', 'CT')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CMP', 'CMP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CON', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CONCRETE BLOCK PIPE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CONCRETE SEGMENTED TUNNEL', 'CSU')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CORRUGATED METAL PIPE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CORRUGATED STEEL PIPE', 'SP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CURED IN PLACE PIPE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('EYE PIPE', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('FIBERGLASS REINFORCED PIPE', 'FRP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('GLASS FIBRE REINFORCED PLASTIC', 'FRP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('HIGH DENSITY POLYETHYLENE', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('KOR FLO PVC PIPE', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('MICRO TUNNELLING CONCRETE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('NON-CORRODE PIPE', 'OB')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('NON-REINFORCED CONCRETE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('NPD', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('OPEN PROFILE PVC - ULTRA RIB', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PERFORATED HDPE', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PERFORATED METAL PIPE', 'SP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PERFORATED SUB DRAIN', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PERFORATED UNDERDRAIN', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PLASTIC LINED PIPE', 'PSC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('POLYETHYLENE PIPE', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('POLYVINYL CHLORIDE', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('POURED IN PLACE CONCRETE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PUD', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PVC', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PVC SEWER SLEEVE', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('REINFORCED CONCRETE', 'RCP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('REINFORCED CONCRETE PIPE', 'RCP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('RUB', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('SANITITE POLYPROPYLENE PIPE', 'PP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('STEEL PIPE', 'SP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('SULPHATE RESISTANT CONCRETE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('TIL', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('UNK', 'XXX')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('UNKNOWN', 'XXX')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('URB', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('VCT - VITRIFIED CLAY TILE PIPE', 'VCP')
  -- NOTE: WEEPING TILE was previously 'PSC' in the old list; newer mapping sets it to 'PVC'. We will apply the newer one below.
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('WOOD STAVE', 'WZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('VITRIFIED CLAY PIPE', 'VCP')

  -- New rows and helpful variants
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('AC', 'AC')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CAMALLOY', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CAST IRON', 'CAS')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('CONCRETE', 'CP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('COPPER', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('GALVINIZED', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('GALVANIZED', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('GI', 'XXX')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('HPLCP', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('HPLC P', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('KITEC', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('LEAD', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('MAN HOLE #', 'XXX')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('NO CORRODE', 'OB')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('PEX', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('POLYETHYLENE', 'PE')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('STEEL', 'SP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('STL', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('TILE', 'VCP')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('TR', 'ZZZ')
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('TRANSITE', 'ZZZ')
  -- Apply newer mapping for WEEPING TILE
  INTO CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE (ivara_material, pioneers_code) VALUES ('WEEPING TILE', 'PVC')
SELECT 1 FROM DUAL;

COMMIT;

Select * from CUSTOMERDATA.EPSEWERAI_MATERIAL_CODE
order by 2,1;