-- Create table permitting NULL pioneer codes
--DROP TABLE CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE
CREATE TABLE CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (
  ivara_material   VARCHAR2(200) CONSTRAINT wallcode_xref_uk UNIQUE,
  pioneers_code    VARCHAR2(20)  -- allow NULL
);

-- Bulk insert all mappings
INSERT ALL
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('BLOCK', 'CR')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('BRICK', 'BR')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('NO CONE', NULL)
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('POURED IN PLACE CONCRETE', 'CN')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('PRECAST CONCRETE', 'CR')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('SLAB TOP', 'CR')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('UNKNOWN', 'XXX')

  -- Bench block
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('MANHOLE PIPE SADDLE', NULL)
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('NO BENCH', 'CR')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('NOT CODED', NULL)
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('PERCHED MANHOLE', NULL)
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('TEE RISER MANHOLE', NULL)

  -- Channel block
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('PIPE', 'PVC')
  INTO CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE (ivara_material, pioneers_code) VALUES ('SUMP', 'CR')
SELECT 1 FROM DUAL;

COMMIT;


Select * from CUSTOMERDATA.EPSEWERAI_WALL_BENCH_CHANNEL_CODE
order by 1;