CREATE OR REPLACE TRIGGER TRG_SYNC_CR_INSPECT_SID
AFTER INSERT OR UPDATE ON CUSTOMERDATA.EPSEWERAI_INSPECTIONS
FOR EACH ROW
BEGIN
    -- Only update when WORKORDER is not null
    IF :NEW.WORKORDER IS NOT NULL THEN
    
        -- Update matching CR_INSPECT rows
        UPDATE CUSTOMERDATA.EPSEWERAI_CR_INSPECT t
        SET t.INSPECTION_SID = :NEW.INSPECTION_SID
        WHERE t.WORKORDER = :NEW.WORKORDER;
        -- NOTE:
        -- If you want to update only rows where INSPECTION_SID IS NULL:
        -- AND t.INSPECTION_SID IS NULL;
        
    END IF;
END;
